# 应用端口
server:
  port: 8777
# 应用名称
app.name: LeoCodeHub
# 应用版本
app.version: 1.0.0
# 应用描述
app.description: LeoCodeHub是一个基于Spring Boot的开源代码分享平台，致力于为程序员提供优质的编程资源。

spring:
  jackson:
    # 设置后台返参，若字段值为 null, 则不返回
    default-property-inclusion: non_null
  profiles:
    # 默认激活 dev 环境
    active: dev



